/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.muscy;

public class Library {
    public boolean someLibraryMethod() {
        System.out.println("Hello demo from Library");
        return true;
    }
}
